const { SlashCommandBuilder, ActionRowBuilder, StringSelectMenuBuilder, ButtonBuilder, ButtonStyle, ChannelType, MessageFlags } = require('discord.js'); // Added ButtonBuilder, ButtonStyle
const { createChannelPaginationMessage } = require('../utils/pagination'); // Import pagination utility

// Define how many channels to show per page in the dropdown
const CHANNELS_PER_PAGE = 25; // Max options for StringSelectMenuBuilder

module.exports = {
    // Defines the slash command's name and description.
    data: new SlashCommandBuilder()
        .setName('channel-set')
        .setDescription('Opens a paginated menu to select multiple channels from a specific category.'),

    // The execute function now sends a message with a StringSelectMenu
    // containing only channels from the specified category for the current page.
    async execute(interaction, db, client) { // db is passed but not used directly in this part of the command
        // NOTE: interaction is already deferred globally in index.js

        const guild = interaction.guild;

        if (!guild) {
            // Use followUp for errors since deferral already occurred
            return await interaction.followUp({ content: 'This command can only be used in a guild.', flags: MessageFlags.Ephemeral });
        }
        
        // Use the centralized utility function to create the initial (Page 0) message components
        // The utility function handles the channel filtering based on TARGET_CATEGORY_ID
        const { content, components } = await createChannelPaginationMessage(guild, 0);

        // Handle case where no channels are found (content will have been updated by utility)
        if (components.length === 0) {
            return await interaction.editReply({
                content: content,
                flags: MessageFlags.Ephemeral
            });
        }
        
        // Send the message with the dropdown and buttons using editReply
        await interaction.editReply({
            content: content,
            components: components, // Components are the two ActionRows generated by the utility
            flags: MessageFlags.Ephemeral
        });
    },
};
